### ISSUE TITLE
creat-react-app

### ISSUE THREAD

**Issue by traceWater** [traceWater/social-media-app#1]
As a developer, I want to use creat-react-app, in order to have a predefined project.

Dependency #4

**Comment by traceWater** [comment]
Complexity 1
Time Box     15

**Comment by traceWater** [comment]
Ready for QA@luceroweb

**Comment by luceroweb** [comment]
@traceWater I don't see your changes in the repo. Please push up your changes so I can take a look.

**Comment by traceWater** [comment]
@luceroweb changes are now pushed to the repo.

**Comment by luceroweb** [comment]
@traceWater I checked the repo, and everything is good. I don't have permissions to close this ticket. Can you please give me permissions in the Project settings?

**Comment by traceWater** [comment]
Unable to at this time, I will go ahead and close the ticket myself.
