### ISSUE TITLE
Create a branch

### ISSUE THREAD

**Issue by traceWater** [traceWater/social-media-app#3]
As a developer, I want to create a development branch, to provide a separate branch from the main for future development.

**Comment by traceWater** [comment]
Complexity 0
Time Box    1

Developer requirements

- Needs know how to create branch in terminal/vs
- The branch must be created
- The developer must separate development branch from main

**Comment by traceWater** [comment]
Ready for QA@luceroweb

**Comment by luceroweb** [comment]
@traceWater  Will you be developing code in this ticket? The ticket reads "to develop code".

**Comment by luceroweb** [comment]
@traceWater Please push up your new branch so I can see it in the repo. What branch did you create? The ticket didn't specify a name for the new branch.

**Comment by traceWater** [comment]
- @luceroweb I edited the user story to make the intent more clear.

- @luceroweb I created and pushed a branch named development.

**Comment by luceroweb** [comment]
@traceWater confirmed! The new user story is perfect and I see the branch is now on here. Please go ahead and close this ticket.
