### ISSUE TITLE
Connect repo to local

### ISSUE THREAD

**Issue by traceWater** [traceWater/social-media-app#4]
As a developer, I need to connect the repo to the local, so that I have a local copy.

**Comment by traceWater** [comment]
Complexity 0
Time box.    10


User Expectations - None

Developer requirements 

- Needs know how to clone down from github
- The repo must be created
- The developer must have access to the repo

**Comment by traceWater** [comment]
Development is complete ready for QA, @luceroweb

**Comment by luceroweb** [comment]
Thanks Dale! I was watching while you completed this ticket and I didn't see any issues. I'm going to mark this ticket as done.
