### ISSUE TITLE
Create feed data storage object

### ISSUE THREAD

**Issue by traceWater** [traceWater/social-media-app#5]
As a developer, I want a json object that can store a post list, so that it will be available to the post form component.

**Comment by traceWater** [comment]
Complexity 1

Time Box - 40min

User expectation - None

developer dependencies:

```
{
   key: value,
}
```

**Comment by traceWater** [comment]
- Need to know how to create a json object
- Need to identify the features, and how to id them in the object

**Comment by luceroweb** [comment]
@traceWater I don't see a data storage object in the repo, so I'm going to re-open this project, and put it back into the "backlog".

**Comment by luceroweb** [comment]
@traceWater what shape with the post data be stored in the data object? I assume you'll need to store the post date, the user who posted it, and the body (including any images), but will you need any other data stored with the post in the data object?

**Comment by luceroweb** [comment]
@traceWater this ticket has not yet been submitted for QA. It should not have been closed. Re-opening and sending back to "In Progress". Please do not close tickets, let me do that.

**Comment by luceroweb** [comment]
@traceWater this ticket was closed without QA approval. Please do not close tickets until I have approved them.
