### ISSUE TITLE
Add Styled Components Package

### ISSUE THREAD

**Issue by luceroweb** [traceWater/social-media-app#6]
As a developer, I need to install the styled components package, so that I can use it in future tickets.

**Comment by traceWater** [comment]
complexity - 0
time box     - 5
user expectations - None

developer requirements

As a developer, I need to know how to use npm to install styled components package.

**Comment by traceWater** [comment]
This ticket is ready for QA

**Comment by luceroweb** [comment]
@traceWater I don't see anything in the repo. Please push up your changes so I can take a look.

**Comment by luceroweb** [comment]
@traceWater I confirmed that the styled component package is in the development branch. This ticket is approved. I am closing the ticket.
